version: '3'
services:
  postgres:
    build:
      context: ./docker/postgres/
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    container_name: postgres
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
